Count Intersection task: enable model upload to Hugging Face Hub
ariG23498/ft-pali-gemma pull request #7
Opened 2024-12-10 16:24 UTC by oliveirabruno01

This PR adds the ability to upload a fine-tuned model for the `count_intersection` task to the Hugging Face Hub, as discussed at #5.  

Changes currently include:  
- Updated the `count_intersection` task to include model upload functionality.
- Refactored the task's notebook for better readability.
- Made minor changes to streamline the workflow.

2024-12-10 16:25 UTC, oliveirabruno01 commented
@ariG23498

2024-12-11 04:49 UTC, ariG23498 requested changes
Thank you for all the work. It is good as is, but left some minor suggestions.

Something you can look into is the `tags` parameter with the `model.push_to_hub`. That would help fine tuned models be tagged with something specific, so that later we can understand how many people used our repo to fine tune their models. WDYT?

Also I think we can keep the notebook as if, it is anyway not meant for direct usage.

2024-12-11 04:49 UTC, ariG23498 commented on count_intersection/create_intersection_dataset.py
> +        ds.push_to_hub(dataset_id)
Neat!

2024-12-11 04:49 UTC, ariG23498 commented on count_intersection/create_intersection_dataset.py
Can we also update the `Example usage` section right at the beginning of the script?
That would help people copy the command and run it. (Not a blocker, but good to have)

2024-12-11 04:49 UTC, ariG23498 commented on count_intersection/README.md
> +  - `dataset_id`: ID (username + dataset name) used to upload to the Hub. Required if `push_to_hub` is True.
Would be a nice idea to show an example of `ID`, feel free to use `ariG23498/intersection-dataset` as the example.

2024-12-11 04:49 UTC, ariG23498 commented on count_intersection/README.md
> +  - `model_id`: ID (username + model name) used to upload to the Hub. Required if `push_to_hub` is True.
Same as above. An example of the ID would be helpful for the user.

2024-12-11 04:49 UTC, ariG23498 commented on count_intersection/README.md
> +1. You may need to authenticate with `huggingface-cli login` if you haven't already.
Great addition.

2024-12-11 04:49 UTC, ariG23498 commented on count_intersection/finetune.py
> +        raise ValueError("model_id cannot be none")
```suggestion
        raise ValueError("`model_id` cannot be `None` when you want to push model to Hub")
```

2024-12-11 04:49 UTC, ariG23498 commented on count_intersection/create_intersection_dataset.py
> +        raise ValueError("dataset_id cannot be None.")
```suggestion
        raise ValueError("`dataset_id` cannot be `None` when you want to push the dataset to Hub")
```

2024-12-11 20:04 UTC, oliveirabruno01 commented
Thank you for your review, @ariG23498. I’ve addressed most of your suggestions, leaving out the `tags` usage and the notebook situation for clarification.

Regarding the notebook, I’m unsure if you meant for it to remain as is or be modified to match the version in my branch.

As for the `tags`, I wanted to clarify with you before proceeding. Would it be acceptable for the `tag` to be the repository name? I also thought it might be useful to include a tag indicating the project task, for example:

```python
if push_to_hub:
    model.push_to_hub(model_id, tags=["fine-tune-paligemma", "count-intersection"])
```

If you could provide some guidance on these points, I’d be happy to continue working on this PR.

Thanks again for your help!

2024-12-12 05:19 UTC, ariG23498 commented
@oliveirabruno01 great work so far!

> Regarding the notebook, I’m unsure if you meant for it to remain as is or be modified to match the version in my branch.

Let's think this through, I had only created the notebook so that people could see the inference images before and during training. I think we should safely remove the notebook, and introduce a logging package ([`wandb`](https://wandb.ai/site/)) in another PR and start a training run. That way we could share the logs and discuss further about reproducibility and also compare different methods later. WDYT?

> As for the tags

Love the idea of having multiple tags, please go ahead with the suggestion.

2024-12-12 11:49 UTC, oliveirabruno01 commented
Thank you for the feedback, @ariG23498. Your plan makes sense, and a separate PR for wandb and training runs sounds like a great idea. I appreciate your guidance!

2024-12-20 05:53 UTC, ariG23498 commented
Hey @oliveirabruno01 do you want me to review the PR?

2024-12-21 04:24 UTC, oliveirabruno01 commented
Oh, forgot to mention—yep, it’s ready for review now!

2024-12-23 05:38 UTC, ariG23498 approved these changes
LGTM!

2024-12-23 05:38 UTC, merged

2024-12-23 05:39 UTC, ariG23498 commented
Thank you for your contribution! 🥳